import type { TweakerRole } from './types';

/**
 * Default role + font configuration. Mirrors a display / body / script / mono /
 * serif system. Every `cssVar` here is a CSS custom property the tweaker rewrites
 * on :root — your stylesheet must actually consume these variables for the swap
 * to be visible. Override via the `roles` prop to fit your own token names.
 */
export const defaultRoles: TweakerRole[] = [
  {
    key: 'display',
    label: 'Display',
    cssVar: '--font-display',
    fallback: 'sans-serif',
    sample: 'ADDICTS OF',
    default: 'Archivo',
    sampleStyle: { fontSize: '1.5rem', fontWeight: 700 },
    fonts: [
      { name: 'Archivo', spec: 'Archivo:wdth,wght@62..125,100..900' },
      { name: 'Inter Tight', spec: 'Inter+Tight:wght@400;700;900' },
      { name: 'Space Grotesk', spec: 'Space+Grotesk:wght@400;500;700' },
      { name: 'Schibsted Grotesk', spec: 'Schibsted+Grotesk:wght@400;700;900' },
      { name: 'Hanken Grotesk', spec: 'Hanken+Grotesk:wght@400;700;900' },
      { name: 'Work Sans', spec: 'Work+Sans:wght@400;700;900' },
      { name: 'Oswald', spec: 'Oswald:wght@400;600;700' },
      { name: 'Anton', spec: 'Anton' },
      { name: 'Bebas Neue', spec: 'Bebas+Neue' },
    ],
  },
  {
    key: 'body',
    label: 'Body',
    cssVar: '--font-sans',
    fallback: 'sans-serif',
    sample: 'Think critically.',
    default: 'Archivo',
    sampleStyle: { fontSize: '1.125rem' },
    fonts: [
      { name: 'Archivo', spec: 'Archivo:wdth,wght@62..125,100..900' },
      { name: 'Inter Tight', spec: 'Inter+Tight:wght@400;500;700' },
      { name: 'Space Grotesk', spec: 'Space+Grotesk:wght@400;500;700' },
      { name: 'Schibsted Grotesk', spec: 'Schibsted+Grotesk:wght@400;500;700' },
      { name: 'Hanken Grotesk', spec: 'Hanken+Grotesk:wght@400;500;700' },
      { name: 'Work Sans', spec: 'Work+Sans:wght@400;500;700' },
      { name: 'Instrument Sans', spec: 'Instrument+Sans:wght@400;500;700' },
      { name: 'Familjen Grotesk', spec: 'Familjen+Grotesk:wght@400;500;700' },
    ],
  },
  {
    key: 'script',
    label: 'Script',
    cssVar: '--font-script',
    fallback: 'cursive',
    sample: 'a Renaissance',
    default: 'Great Vibes',
    sampleStyle: { fontSize: '1.875rem' },
    fonts: [
      { name: 'Great Vibes', spec: 'Great+Vibes' },
      { name: 'Pinyon Script', spec: 'Pinyon+Script' },
      { name: 'Ballet', spec: 'Ballet' },
      { name: 'Monsieur La Doulaise', spec: 'Monsieur+La+Doulaise' },
      { name: 'Ephesis', spec: 'Ephesis' },
      { name: 'Allura', spec: 'Allura' },
      { name: 'Alex Brush', spec: 'Alex+Brush' },
      { name: 'Sacramento', spec: 'Sacramento' },
      { name: 'Tangerine', spec: 'Tangerine:wght@400;700' },
      { name: 'Parisienne', spec: 'Parisienne' },
      { name: 'Imperial Script', spec: 'Imperial+Script' },
      { name: 'Herr Von Muellerhoff', spec: 'Herr+Von+Muellerhoff' },
    ],
  },
  {
    key: 'mono',
    label: 'Mono',
    cssVar: '--font-mono',
    fallback: 'monospace',
    sample: '3 : 4 : 5 : 7',
    default: 'IBM Plex Mono',
    sampleStyle: { fontSize: '1.125rem' },
    fonts: [
      { name: 'IBM Plex Mono', spec: 'IBM+Plex+Mono:wght@400;500;600' },
      { name: 'Space Mono', spec: 'Space+Mono:wght@400;700' },
      { name: 'JetBrains Mono', spec: 'JetBrains+Mono:wght@400;500;600' },
      { name: 'DM Mono', spec: 'DM+Mono:wght@400;500' },
      { name: 'Fragment Mono', spec: 'Fragment+Mono' },
      { name: 'Red Hat Mono', spec: 'Red+Hat+Mono:wght@400;500;600' },
      { name: 'Martian Mono', spec: 'Martian+Mono:wght@400;600' },
    ],
  },
  {
    key: 'serif',
    label: 'Serif',
    cssVar: '--font-serif',
    fallback: 'serif',
    sample: 'It will be assembled.',
    default: 'Instrument Serif',
    sampleStyle: { fontSize: '1.25rem' },
    fonts: [
      { name: 'Instrument Serif', spec: 'Instrument+Serif:ital@0;1' },
      { name: 'Playfair Display', spec: 'Playfair+Display:ital,wght@0,400;0,700;1,400' },
      { name: 'Cormorant Garamond', spec: 'Cormorant+Garamond:ital,wght@0,400;0,600;1,400' },
      { name: 'EB Garamond', spec: 'EB+Garamond:ital,wght@0,400;1,400' },
      { name: 'Fraunces', spec: 'Fraunces:ital,wght@0,400;0,700;1,400' },
      { name: 'DM Serif Display', spec: 'DM+Serif+Display:ital@0;1' },
      { name: 'Newsreader', spec: 'Newsreader:ital,wght@0,400;1,400' },
      { name: 'Libre Caslon Text', spec: 'Libre+Caslon+Text:ital,wght@0,400;1,400' },
    ],
  },
];
